### ISSUE TITLE
[dcc32 Error] uMain.pas(74): E2018 Record, object or class type required

### ISSUE THREAD

**Issue by amadeujunior18** [sacfiscal/Delphiscal#3]
![image](https://user-images.githubusercontent.com/6089726/172521020-fe67bc49-3817-41af-a454-32914433335c.png)

**Comment by amadeujunior18** [comment]
![image](https://user-images.githubusercontent.com/6089726/172520807-9745c6ab-3992-4e60-a503-065c6b80ee6a.png)

**Comment by viniciussanchez** [comment]
Resolvido no commit aa988c6c83ffe59a335614fad0843d83e3836f3b
